#!/usr/bin/env bash

# Make vim the default editor
export EDITOR=/usr/bin/vim;

export HISTCONTROL=ignoreboth;
# Make some commands not show up in history
export HISTIGNORE="p:v:vim *:ls *:ll:lsd:cd *:pwd:exit:logout:date:* --help:* -h:history:"

